### ISSUE TITLE
Font does not contain GF Core glyph set

### ISSUE THREAD

**Issue by aaronbell** [Outfitio/Outfit-Fonts#1]
The font is missing 104 glyphs from the [Google Fonts Core glyph set](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam). 

These glyphs should be added to the font.

**Comment by davelab6** [comment]
I'm OK to launch the family in GF given these will be added in an upcoming update

**Comment by andyfitz** [comment]
Confirmed @rfuenzalida has begun work on the update to resolve this ♥️

**Comment by andyfitz** [comment]
This has been resolved, and I couldn't be more thrilled.

**Comment by andyfitz** [comment]
@davelab6  FYI
