### ISSUE TITLE
Corrupted Outfit font in Adobe InDesign (MacOS)

### ISSUE THREAD

**Issue by sidewaysdesign** [Outfitio/Outfit-Fonts#13]
I installed the Outfit static TTFs from Google’s font family download feature a few weeks ago for a client, and it has **twice** simply vanished from InDesign’s font menu in the middle of editing a layout.

Outfit will not reappear even after clearing font caches and reinstalling via Font Book.

The only solution that’s worked is to reinstall InDesign — and then installing fresh copies of Outfit via Font Book. Obviously this obliterates many application settings and is not a long-term solution.

Loading the font into Font Forge, I am noticing that there are many characters with overlapping shapes, which AFAIK is not permitted in TrueType.

A second signal that something is odd about Outfit is that the Webfont Generator in Font Squirrel flatly reports it as corrupt when uploading. Notably, the variable weight version of Outfit does load into Font Squirrel (though that version isn't working in InDesign either).

**Comment by andyfitz** [comment]
Hi @sidewaysdesign  could you please use our upstream OTF files when dealing with desktop software,  google subset our typeface to remove stylistic alternates etc 

The ttf in our repository is specifically for the variable font use on the web
