### ISSUE TITLE
Support for polish language

### ISSUE THREAD

**Issue by wesolowskipatryk** [Outfitio/Outfit-Fonts#16]
Hey,

I found your font on Fontshare and I must admit, I love it. I would like to use it, but support for polish language is missing. Unfortunately, I don't know how to create. I believe that you have full of work, but let me ask. Are you going to add polish characters?

**Comment by gralin** [comment]
If #17 gets merged, it adds the missing polish characters. Outfit Regular example:

![image](https://user-images.githubusercontent.com/3457048/197535431-485dc073-a2c8-4996-8725-785685e339ec.png)
