### ISSUE TITLE
Adding Ō, ō to Outfit

### ISSUE THREAD

**Issue by Nelou5** [Outfitio/Outfit-Fonts#18]
Greetings !

First of all, thank you for your amazing work !
I would like to know if it were possible to add the ō to the font. 

We are using it quite a lot as we are working with Japanese romanized words, and we're missing this letter (might need some others at some point, but for now, just this one would be a huge help)

Thanks for reading me, have a great day !

**Comment by wayne-shih** [comment]
hey @Nelou5 
I've got a fork of Outfit that includes macrons (ie. Ō, ō) and extended latin diacritics support 
Waiting on a review to be merged upstream here
However, as long as you're not relying on google fonts as webfont distribution, you can download the fork release via https://github.com/wayne-shih/Outfit-Fonts/releases/tag/1.100

**Comment by andyfitz** [comment]
Thanks @wayne-shih the change is now merged and in a stable release ready for Google Fonts to do their thing.

Thanks for waiting!
