### ISSUE TITLE
Change vertical metrics

### ISSUE THREAD

**Issue by aaronbell** [Outfitio/Outfit-Fonts#3]
The current vertical metrics do not follow Google's guidance: https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics

Please take a look at make adjustments. Though, I should note that it would be worth adding the accented characters first, though, as these metrics will need to be adjusted to account for the height of `À` (per https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics#concrete-cases).

**Comment by andyfitz** [comment]
That's good advice, thanks Aaron

**Comment by davelab6** [comment]
This does need to be fixed before we add the fonts to GF :)

**Comment by andyfitz** [comment]
Agreed @rfuenzalida is on this currently

**Comment by aaronbell** [comment]
Hi @andyfitz, wanted to check in on the status of this update. Will you be able to push a new version of the font this week? Thanks!

**Comment by andyfitz** [comment]
@aaronbell  this is now done :)  the new version is online

**Comment by aaronbell** [comment]
Great!
