### ISSUE TITLE
Inconsistency with the 'outfit'-ligature

### ISSUE THREAD

**Issue by HenkBarreveld** [Outfitio/Outfit-Fonts#7]
From the website outfit.io:

![image](https://user-images.githubusercontent.com/11945275/142639653-3cd2e71c-6103-4790-9411-ffd513ca97a8.png)

Thanks to ligatures, but there is also:

![image](https://user-images.githubusercontent.com/11945275/142639354-7232639d-1547-491c-ba71-0876dcb7d999.png)

This is not nice...

**Comment by andyfitz** [comment]
Hey this intentional as we only wanted to support the lowercase ligature. This might change in future or we might just add a 'tfi' liga but for now this behaviour was deliberate.  Thanks for your input

**Comment by HenkBarreveld** [comment]
Hi Andy,

Thank you for your explanation and I am sorry for your trouble; you already made this clear in reply to earlier comments on GitHub.

Please be aware that on the outfit.io website the word "Outfit" is used extensively. I just checked the website front page and counted two occurrences of "outfit" (top-left and bottom-right corners) and five times "Outfit": 

- in the menu at the top of the page: "outfit  Solutions   Why Outfit   Pricing   Discover"
- "Outfit will revolutionise how you get on-brand content to market"
- "...sitting it with only a few people with design skills and design software is limiting and creates frustration. Enter Outfit."
- "The Outfit platform is a new breed of online brand management"
- "Outfit Support" (underneath About Us)
- "© Copyright Outfit 2021"

This strongly suggests that "Outfit" is the brand name and that "outfit" in your nice lettering with the ligature and a somewhat heavier font-weight is used as the logo. However, it seems there is also the real "outfit" logo on the page, three times in the picture  at the top, and that logo uses a different lettering. This does not look right, in particular not for a company that offers services to "Build Brands Better". 

Still, I quite like your font!
