### ISSUE TITLE
Please add hungarumlaut accents.

### ISSUE THREAD

**Issue by ultramansurfer** [Outfitio/Outfit-Fonts#8]
I found the typeface really appealing, but I wish it contained the characters (O, U with hungarumlaut accents - Ő, Ű, ő, ű).
Are you considering adding it to the typeface in the near future?

Thank you in advance!

**Comment by andyfitz** [comment]
We are open to PR's that add this.  It's certainly welcome

**Comment by wayne-shih** [comment]
heads up, I'm working on extending it to [GF Latin Core glyph set](https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/prod-names/GF_Latin_Core.txt) coverage (which includes hungarumlaut accents) as part of a wider font modification project. 

will do a PR of the extension itself with all the on-brand flair in tact when it's in a good enough state

for now, still a fair bit to go 
https://wayne-shih.github.io/Outfit-Fonts/glyphs.html 

and if you want to get the WIP files... download it via the artefacts of GH builds 
https://github.com/wayne-shih/Outfit-Fonts/actions/workflows/build.yaml

**Comment by kenmcd** [comment]
> heads up, I'm working on extending it to [GF Latin Core glyph set](https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/prod-names/GF_Latin_Core.txt) coverage (which includes hungarumlaut accents) as part of a wider font modification project.
> 
> will do a PR of the extension itself with all the on-brand flair in tact when it's in a good enough state
> 
> for now, still a fair bit to go https://wayne-shih.github.io/Outfit-Fonts/glyphs.html
> 
> and if you want to get the WIP files... download it via the artefacts of GH builds https://github.com/wayne-shih/Outfit-Fonts/actions/workflows/build.yaml

Please enable the Issues tracker so people who would like help can post.

**Comment by wayne-shih** [comment]
hey @kenmcd 
sorry won't be doing that for now. the changes done now on my own fork (prior to opening a PR) is provided as is and I won't be accepting any changes nor am I looking for help at this point. 
I think the place for discussion will be on the PR itself once it's opened -- there's still a fair bit to do from now till then
